### ISSUE TITLE
Discord ban

### ISSUE THREAD

**Issue by supertiger1234** [GhostSelfbot/Ghost#11]
Did you like that discord ban, Ben Tettmar? 😉 

~ Pankeki, the reporter.

**Comment by supertiger1234** [comment]
Sure bud lol. Add me as friend then to prove.

**Comment by timof121** [comment]
brain issue

**Comment by timof121** [comment]
im using this like for 3+ months even with abuse cmds and nothing bad happened

**Comment by supertiger1234** [comment]
Who asked. I'm talking to Ben lool

**Comment by bentettmar** [comment]
This funny

**Comment by timof121** [comment]
> Who asked. I'm talking to Ben lool

you literally "asked" in the issue, you made a statement, I rejected it💀

**Comment by supertiger1234** [comment]
What

**Comment by Innocence303** [comment]
dumfuk
