### ISSUE TITLE
HELP AGAIN

### ISSUE THREAD

**Issue by GolemGreat** [GhostSelfbot/Ghost#16]
i can't run it as all i get is
![Capture](https://user-images.githubusercontent.com/82716520/144115288-865d046a-6411-428b-b6e8-056920bc4747.PNG)

**Comment by bentettmar** [comment]
try the following commands:
```
pip uninstall discord.py
pip install discord.py-self
```

if that doesn't work, you can try downloading the `requirements.txt` and running `pip install -r requirements.txt` in the same folder that the `requirements.txt` is in.

**Comment by GolemGreat** [comment]
i still get the same error

**Comment by bentettmar** [comment]
Try running the commands in [this](https://github.com/GhostSelfbot/Ghost/issues/4#issuecomment-955428224) comment.

**Comment by bentettmar** [comment]
Didn't mean to close it *

**Comment by GolemGreat** [comment]
i did but i still get this error i have tried on different self bots and none of them work

**Comment by bentettmar** [comment]
then its an issue on your end, ive tried my best to help you.

_tip: join our [discord](https://discord.gg/aWTpaJV4cT) for faster support__

**Comment by timof121** [comment]
Try uninstalling discord.py, and then FORCE reinstall discord.py-self

**Comment by hiraxx214** [comment]
i had the same problem i just uninstall discord.py and discord.py-self then reinstall them
