### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by Kwenma1** [GhostSelfbot/Ghost#25]
list index out of range

**Comment by timof121** [comment]
what

**Comment by Kwenma1** [comment]
it gives me an error when trying to open it after I put my discord token

**Comment by Kwenma1** [comment]
the error is:list index out of range

**Comment by bentettmar** [comment]
send a screenshot of the error

**Comment by Kwenma1** [comment]
![image](https://user-images.githubusercontent.com/95584786/149634708-37071fe0-7a0a-4f0a-b960-1a591c2876ae.png)

**Comment by bentettmar** [comment]
thats not enough info for me to help you

**Comment by Kwenma1** [comment]
Then what do i post for u to be able to help me?

**Comment by Kwenma1** [comment]
[info.log](https://github.com/GhostSelfbot/Ghost/files/7875703/info.log)


heres the log if u want it

**Comment by timof121** [comment]
try with python 3.8+

**Comment by Kwenma1** [comment]
mk

**Comment by Kwenma1** [comment]
Thank you it works.
