### ISSUE TITLE
Giveaway Sniper Bug

### ISSUE THREAD

**Issue by Krishvy** [GhostSelfbot/Ghost#27]
It doesn't auto enter giveaways, although it does show the giveaway in the Terminal.

**Comment by timof121** [comment]
happens to me when i use python 3.8, try getting 3.9+

**Comment by bentettmar** [comment]
> It doesn't auto enter giveaways, although it does show the giveaway in the Terminal.

Have you added the giveaway bot with the emoji you need to use to react with in `giveawaybots.json`?

**Comment by timof121** [comment]
inactive
