### ISSUE TITLE
virgin 

### ISSUE THREAD

**Issue by cliphd** [GhostSelfbot/Ghost#28]
bro spent his time programming like 10k lines of code for a discord selfbot 💀

**Comment by mikey1538** [comment]
It was a Paid selfbot then it got cracked

**Comment by mikey1538** [comment]
you stupid waste of oxygen

**Comment by bentettmar** [comment]
> bro spent his time programming like 10k lines of code for a discord selfbot 💀 

It used to be a paid selfbot and private. Due to some allegations u (the original developer) decided to make the code open source.

**Comment by timof121** [comment]
> bro spent his time programming like 10k lines of code for a discord selfbot 💀

It was paid, now open source

**Comment by abashir7866** [comment]
balls

**Comment by Robberies** [comment]
> balls

fr

**Comment by Robberies** [comment]
:skull: 

![](https://host.femboy.sh/u/rUJfTiek.png)

**Comment by timof121** [comment]
> 💀
> 
> ![](https://camo.githubusercontent.com/427fc6726021256f319e481c0c3a7a5f0ddf6683869650e1381f065110304d99/68747470733a2f2f686f73742e66656d626f792e73682f752f72554a665469656b2e706e67)

LOL
