### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by Drew-Xbox-FOR3V3RUP** [ghostselfbot/ghost#3]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/ghost/ghost.py", line 40, in <module>
    ghost = commands.bot(
            ^^^^^^^^^^^^^
TypeError: 'module' object is not callable

Pops up when trying to start the bot

**Comment by bennyscripts** [comment]
Before you follow the below steps, **you must** pull the most recent changes.

1. Create a virtual python environment.
2. Activate the virtual environment.
3. Install the requirements in `requirements.txt` using `pip install -r requirements.txt`.
4. Run `ghost.py`.
