### ISSUE TITLE
I put my token in config and not working

### ISSUE THREAD

**Issue by stamply** [GhostSelfbot/Ghost#33]
It says invalid or non working token when it is working I just copied my token

**Comment by D1trox** [comment]
try this: 
pip uninstall discord.py
pip uninstall discord.py-self
Then install only discord.py-self by using:
pip install discord.py-self

**Comment by timof121** [comment]
> It says invalid or non working token when it is working I just copied my token

i specifically made a troubleshooting wiki page for that
https://github.com/GhostSelfbot/Ghost/wiki/Troubleshooting

**Comment by Kwenma1** [comment]
Do these commands:
pip uninstall discord.py
pip uninstall discord.py-self
pip install discord.py-self
