### ISSUE TITLE
ghost image commands not working

### ISSUE THREAD

**Issue by RavenZReal** [GhostSelfbot/Ghost#45]
![Capture](https://user-images.githubusercontent.com/77937903/155572625-f9efd2d1-f17a-450a-bf8a-d453d9eb16f7.PNG)
i have tried everything but it just stopped working

**Comment by abashir7866** [comment]
I believe those apis are dead

**Comment by RavenZReal** [comment]
> I believe those apis are dead

how do i fix it?

**Comment by abashir7866** [comment]
You can't, the api itself that makes the image is dead. Maybe finding another api and replacing the code can fix it

**Comment by RavenZReal** [comment]
um so its a problem with everyone not just me?

**Comment by RavenZReal** [comment]
i just checked yes it is a problem for everyone but how do i find a new api or i should just wait for a few days and the owners will fix it?

**Comment by timof121** [comment]
im a retard

**Comment by timof121** [comment]
1 sec ill put new domain sinece i wtiched domain

**Comment by timof121** [comment]
fixed in dev branch

**Comment by Shkeffy** [comment]
> fixed in dev branch

Where can I find the dev branch?
