### ISSUE TITLE
quick question

### ISSUE THREAD

**Issue by never-mind-who** [GhostSelfbot/Ghost#50]
how can i massdm a server if i don t have permissions to write

**Comment by DrkTheDon** [comment]
You cant xd?

**Comment by bentettmar** [comment]
> how can i massdm a server if i don t have permissions to write

If you mean that you dont have permission to send messages in channels in the server but there are members in the server that have their DMs open. Then you can massdm but you will need to find a tool that will do it without using a selfbot.
