### ISSUE TITLE
how can i put multiple tokens

### ISSUE THREAD

**Issue by MihaiGamerYT54** [GhostSelfbot/Ghost#51]
my brain is the size of a rice grain and i cannot find out how can i use multiple tokens

**Comment by bentettmar** [comment]
Multiple tokens can only be used with the raid tools which are now deprecated and most likely will get your tokens locked. But, to do so, open data/tokens.txt and paste your tokens line by line and then launch ghost and use the raid commands that use multiple tokens.

**Comment by MihaiGamerYT54** [comment]
thanks
