### ISSUE TITLE
help

### ISSUE THREAD

**Issue by a2hg** [GhostSelfbot/Ghost#52]
Loading Ghost...
 
Resetting info log.
Resetting warning log.
Resetting error log.
Resetting critical log.
 
PortAudio library not found
Press enter to close . . .

**Comment by bentettmar** [comment]
Please look at the following stackoverflow answer.
https://stackoverflow.com/a/50248835

**Comment by timof121** [comment]
sudo apt install portaudio-dev -y

**Comment by timof121** [comment]
or whatever it was
