### ISSUE TITLE
No module named 'winshell'

### ISSUE THREAD

**Issue by Righted1** [GhostSelfbot/Ghost#57]
title literally says it all. even though its installed, ghost doesnt recognise it,

**Comment by abashir7866** [comment]
If you installed it through the requirements it's actually not installed, it's a bug in the installer that ill fix later. Run pip install winshell

**Comment by Righted1** [comment]
> If you installed it through the requirements it's actually not installed, it's a bug in the installer that ill fix later. Run pip install winshell

I've ran that already. first i uninstalled it then reinstalled it again, after that i ran it again and still didn't work.

**Comment by timof121** [comment]
Hey Righted1!
![reverse](https://user-images.githubusercontent.com/52547763/166677766-a66f789d-9418-4e47-8df6-5fef656e0cf7.png)
We appreciate and hear your feedback. Thanks for contacting us!
