### ISSUE TITLE
Replit

### ISSUE THREAD

**Issue by Shkeffy** [GhostSelfbot/Ghost#58]
Does this work on Replit?

**Comment by natethemaker** [comment]
yes but you cant use a .replit file you have to start it in the shell with `python ./Ghost.py`

**Comment by sigmaclientwastaken** [comment]
if you want to leak your token, yes

**Comment by Shkeffy** [comment]
> if you want to leak your token, yes

I have hacker, don't worry.

**Comment by Shkeffy** [comment]
It all works!

**Comment by Shkeffy** [comment]
@natethemaker will it do 'always on'??
Because it technically uses Shell...

**Comment by Shkeffy** [comment]
@sigmaclientwastaken @timof121 @BobIsMyManager

**Comment by Shkeffy** [comment]
Could someone please help me?

**Comment by Shkeffy** [comment]
Never mind, I used hacker and gave it 'Always On', and it somehow works!

**Comment by natethemaker** [comment]
if you give it a HTTP server I will try to work it out

**Comment by natethemaker** [comment]
`https://replit.com/github/natethemaker/GhostReplit` to use w/ replit
