### ISSUE TITLE
Powershell colours not working

### ISSUE THREAD

**Issue by jbsparrow** [GhostSelfbot/Ghost#62]
the package `sty`'s rgb colours do not work on Windows Powershell.

`colorama.Fore` and `sty.fg` colours do work in powershell, although they do need to be initialized by including `colorama.init()`.

The issue here is that Ghost does not look at what shell it is running in on Windows, meaning that somebody using powershell won't get any colour.

**Comment by timof121** [comment]
is it Windows Terminal from ms store or raw PS

**Comment by timof121** [comment]
![reverse](https://user-images.githubusercontent.com/52547763/167167308-1f91b6b3-3995-4d96-8514-f6b1c97db93f.png)

**Comment by Shkeffy** [comment]
@jbsparrow Please answer the question or the issue will close.

**Comment by abashir7866** [comment]
Mans acting like a fucking discord mod LMAOOO

**Comment by Shkeffy** [comment]
@abashir7866 Tf? Chill out, mate.

**Comment by abashir7866** [comment]
Bro shits hilarious

**Comment by Shkeffy** [comment]
@abashir7866 You're mad weird. Go touch grass.

**Comment by Shkeffy** [comment]
Bye.

**Comment by abashir7866** [comment]
Lmao funny shit

**Comment by jbsparrow** [comment]
> @jbsparrow Please answer the question or the issue will close.

Sorry, @Shkeffy, I was busy. Are you against people sending memes in general? Better go check on your kitten, she's in vc with another eboy 😰😖😖

@timof121 It is raw powershell.

**Comment by Shkeffy** [comment]
> > @jbsparrow Please answer the question or the issue will close.
> 
> Sorry, @Shkeffy, I was busy. Are you against people sending memes in general? Better go check on your kitten, she's in vc with another eboy 😰😖😖

I- wha-?

**Comment by IVRAirheadI** [comment]
OMG HI GUYS i found new general chat

**Comment by abashir7866** [comment]
Vrheadass is here let's go guys

**Comment by jbsparrow** [comment]
OMG VRAIRHEAD OMG OMG ONG IM A HUGE FAN!! WE SHOULD BE BEST FRIENDS ON GITHUB YOU ARE SO COOL!! PLEASE DONT STEAL MY DISCORD KITTEN 😫

**Comment by timof121** [comment]
hello dead chat reviv pls @everyone

**Comment by jbsparrow** [comment]
@abashir7866 @Shkeffy @timof121 @IVRAirheadI @bentettmar

**Comment by jbsparrow** [comment]
> > @abashir7866 @Shkeffy @timof121 @IVRAirheadI @bentettmar
> 
> 
> 
> Shaddup.

Did you mean to say: "Shabbat"?

**Comment by abashir7866** [comment]
I shat my pants

**Comment by jbsparrow** [comment]
> I shat my pants

Can I see?
