### ISSUE TITLE
Replit running.

### ISSUE THREAD

**Issue by Shkeffy** [GhostSelfbot/Ghost#63]
So, the Replit Dev version doesn't run with the run button, so it cannot be made to work 24/7, which is annoying. The original had a bug where if you spammed the run button, it worked. This one doesn't. Does anyone have a way of it being able to actually *run* on Replit other than entering 'python ./Ghost.py' on Replit console?

**Comment by sigmaclientwastaken** [comment]
replit generates a .replit file which contains stuff like whats run when clicking the run button

**Comment by Shkeffy** [comment]
@sigmaclientwastaken The button runs it for a millisecond.

**Comment by Shkeffy** [comment]
And then it says 'run' again.

**Comment by sigmaclientwastaken** [comment]
> @sigmaclientwastaken The button runs it for a millisecond.

what I'm saying is that you could probably find a way to do it by modifying stuff in that file

**Comment by Shkeffy** [comment]
Uploading Run.mp4…

**Comment by Shkeffy** [comment]
https://user-images.githubusercontent.com/97449528/167212482-8b62c6fb-57ca-4fdc-936a-c2e91a0c0f22.mp4

**Comment by Shkeffy** [comment]
> > @sigmaclientwastaken The button runs it for a millisecond.
> 
> what I'm saying is that you could probably find a way to do it by modifying stuff in that file

That's what I was asking help with lol.

**Comment by sigmaclientwastaken** [comment]
> > > (can this terrible app stop pinging me when someone quotes a reply) The button runs it for a millisecond.
> > 
> > what I'm saying is that you could probably find a way to do it by modifying stuff in that file
> 
> That's what I was asking help with lol.

oh i didn't read it correctly

**Comment by Shkeffy** [comment]
Yeah... so *do* you know how to help?

**Comment by Shkeffy** [comment]
@sigmaclientwastaken

**Comment by Shkeffy** [comment]
I figured it out.
